import Link from "next/link";
import type { Metadata } from "next";
import {
  PublicShell,
  Container,
  Section,
  SectionLabel,
  PageHero,
  Callout,
  DefinitionCard,
  T,
  DOWNLOAD_URL,
  SITE_URL,
} from "@/components/public/shell";
import {
  LocalAgentArchitectureDiagram,
  ManualVsControlledDiagram,
  RiskEngineDiagram,
  TradeManagementDiagram,
} from "@/components/public/diagrams";

export const metadata: Metadata = {
  title: "Features | Apex Quantel",
  description:
    "Explore Apex Quantel features including local MT5 execution, private signal routing, risk checks, position sizing, trade management, and dashboard monitoring.",
  alternates: { canonical: "/features" },
  openGraph: {
    title: "Features | Apex Quantel",
    description:
      "Explore Apex Quantel features including local MT5 execution, private signal routing, risk checks, position sizing, trade management, and dashboard monitoring.",
    url: `${SITE_URL}/features`,
    siteName: "Apex Quantel",
    images: [{ url: `${SITE_URL}/apex-quantel-og.png`, width: 1200, height: 630, alt: "Apex Quantel Features", type: "image/png" }],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Features | Apex Quantel",
    description: "Local MT5 execution, private signal routing, risk checks, and trade management.",
    images: [`${SITE_URL}/apex-quantel-og.png`],
  },
};

// ── Local helpers ────────────────────────────────────────────────────────────

function FeatureHeader({ label, heading, sub }: { label: string; heading: string; sub: string }) {
  return (
    <div style={{ marginBottom: 28 }}>
      <SectionLabel text={label} />
      <h2 style={T.h2}>{heading}</h2>
      <p style={{ ...T.body, maxWidth: 560 }}>{sub}</p>
    </div>
  );
}

function CheckList({ items }: { items: string[] }) {
  return (
    <ul style={{ margin: "16px 0 0", padding: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: 9 }}>
      {items.map((item) => (
        <li key={item} style={{ display: "flex", alignItems: "flex-start", gap: 10 }}>
          <span style={{ width: 4, height: 4, borderRadius: "50%", background: "var(--line-strong)", marginTop: 9, flexShrink: 0 }} />
          <span style={{ ...T.body, fontSize: 13.5 }}>{item}</span>
        </li>
      ))}
    </ul>
  );
}

// ── Page ─────────────────────────────────────────────────────────────────────

export default function FeaturesPage() {
  return (
    <PublicShell>
      <main>
        <PageHero
          label="Platform features"
          heading="What the platform does."
          sub="A structured breakdown of each component in the Apex Quantel execution system — from signal receipt to trade management."
        />

        {/* 01 — Local Execution Agent */}
        <Section surface>
          <Container>
            <FeatureHeader
              label="01 — Execution agent"
              heading="Local MT5 execution."
              sub="The AQ Agent is a Windows desktop application that connects directly to a local MetaTrader 5 terminal and executes orders on behalf of the user."
            />
            <div className="grid md:grid-cols-2 gap-10 items-start">
              <div>
                <p style={T.body}>
                  The agent runs on the same Windows machine as MetaTrader 5. It communicates with
                  the MT5 terminal through the MetaTrader 5 Python API, placing and managing orders
                  through the broker connection already established by the terminal.
                </p>
                <p style={{ ...T.body, marginTop: 14 }}>
                  Execution does not route through a cloud server. All order placement happens
                  locally. MT5 credentials remain on the user&apos;s machine.
                </p>
              </div>
              <div className="min-w-0">
                <LocalAgentArchitectureDiagram />
              </div>
            </div>
          </Container>
        </Section>

        {/* 02 — Private Signal Routing */}
        <Section>
          <Container>
            <FeatureHeader
              label="02 — Signal routing"
              heading="Private signal distribution."
              sub="Trading signals are routed through the Apex Quantel gateway to licensed users only. Signals are not publicly broadcast."
            />
            <div className="grid md:grid-cols-2 gap-10 items-start">
              <div>
                <p style={T.body}>
                  When a signal is generated by the signal source, it is transmitted to the gateway
                  with a cryptographic signature. The gateway validates the signal and verifies that
                  the receiving user holds an active licence before forwarding it to their connected
                  AQ Agent.
                </p>
                <p style={{ ...T.body, marginTop: 14 }}>
                  Each signal carries the information needed for execution: symbol, direction (long
                  or short), entry price, stop loss level, and take-profit targets.
                </p>
              </div>
              <div>
                <DefinitionCard
                  term="Gateway"
                  definition="The Apex Quantel server component that receives signals from the signal source, validates them, and distributes them to connected AQ Agents with active licences."
                />
              </div>
            </div>
          </Container>
        </Section>

        {/* 03 — Risk Checks */}
        <Section surface>
          <Container>
            <FeatureHeader
              label="03 — Risk enforcement"
              heading="Risk checks before entry."
              sub="Before placing any order, the execution engine runs a series of validation checks against the configured risk rules and current account state."
            />
            <div className="grid md:grid-cols-2 gap-10 items-start">
              <div>
                <p style={T.body}>
                  Risk checks run synchronously before order placement. If any check fails, the
                  trade is rejected and the rejection reason is logged. The engine does not attempt
                  to place an order that fails validation.
                </p>
                <Callout type="note">
                  Risk parameters are configurable. Default values are conservative by design, but
                  users are responsible for setting limits appropriate to their account size and
                  risk tolerance.
                </Callout>
              </div>
              <div className="min-w-0">
                <RiskEngineDiagram />
              </div>
            </div>
          </Container>
        </Section>

        {/* 04 — Position Sizing */}
        <Section>
          <Container>
            <FeatureHeader
              label="04 — Position sizing"
              heading="Risk-based lot calculation."
              sub="The engine calculates trade size from the configured risk percentage and the stop distance, rather than requiring manual lot entry."
            />
            <div className="grid md:grid-cols-2 gap-10 items-start">
              <div>
                <p style={T.body}>
                  For each trade, the engine determines the monetary risk amount from the configured
                  risk percent applied to the current account balance. It then calculates the lot
                  size required so that if the stop loss is hit, the loss equals that risk amount.
                </p>
                <p style={{ ...T.body, marginTop: 14 }}>
                  The calculated lot size is validated against configured minimum and maximum bounds
                  and adjusted to the broker&apos;s lot step before the order is placed.
                </p>
              </div>
              <div>
                <DefinitionCard
                  term="Position sizing"
                  definition="The process of calculating how many lots to trade based on: account balance, configured risk percent, stop loss distance in pips, and the pip value of the symbol. The result is a lot size that limits the potential loss to the configured risk amount."
                />
              </div>
            </div>
          </Container>
        </Section>

        {/* 05 — Trade Management */}
        <Section surface>
          <Container>
            <FeatureHeader
              label="05 — Trade management"
              heading="Breakeven, partial TP, and position tracking."
              sub="After order placement, the engine monitors open positions and applies the configured management logic at each price level."
            />
            <div className="grid md:grid-cols-2 gap-10 items-start">
              <div>
                <p style={T.body}>
                  Once a position is open, the engine polls its state continuously. When the price
                  reaches the TP1 trigger level, the engine applies the configured management
                  actions before the position continues toward the full target.
                </p>
                <CheckList
                  items={[
                    "TP1 trigger: configurable percent of the SL-to-TP distance",
                    "Breakeven: stop loss moved to the original signal entry price after TP1",
                    "Partial close: configurable percent of position closed at TP1",
                    "TP2: remaining position closed at full take-profit",
                    "Expiry: positions tracked against signal lifetime",
                    "Execution events logged at each management action",
                  ]}
                />
              </div>
              <div className="min-w-0">
                <TradeManagementDiagram />
              </div>
            </div>
          </Container>
        </Section>

        {/* 06 — Dashboard */}
        <Section>
          <Container>
            <FeatureHeader
              label="06 — Dashboard"
              heading="Visibility and control."
              sub="The web dashboard provides access to account management, agent monitoring, signal history, execution events, and billing — without touching the local agent directly."
            />
            <div
              className="grid sm:grid-cols-2 md:grid-cols-3"
              style={{ gap: 1, background: "var(--line-soft)", border: "1px solid var(--line-soft)", borderRadius: 10, overflow: "hidden", marginTop: 8 }}
            >
              {(
                [
                  ["Signal feed", "View incoming signals, their status, and execution outcomes."],
                  ["Execution events", "A log of trade placements, rejections, management actions, and closes."],
                  ["Engine status", "Connection state of the AQ Agent, MT5 link, and gateway."],
                  ["Licence management", "View, activate, and manage licence keys."],
                  ["Billing", "Manage subscription and payment details."],
                  ["Agent download", "Access the current AQ Agent installer."],
                ] as [string, string][]
              ).map(([title, body]) => (
                <div key={title} style={{ padding: "18px 20px", background: "var(--base)" }}>
                  <div style={{ fontSize: 12, fontWeight: 700, color: "var(--text-soft)", marginBottom: 5 }}>
                    {title}
                  </div>
                  <div style={{ fontSize: 13, color: "var(--muted)", lineHeight: 1.65 }}>{body}</div>
                </div>
              ))}
            </div>
          </Container>
        </Section>

        {/* Comparison */}
        <Section surface>
          <Container>
            <SectionLabel text="Comparison" />
            <h2 style={T.h2}>Manual execution vs. AQ Agent execution.</h2>
            <p style={{ ...T.body, marginBottom: 28 }}>
              The agent addresses the execution layer that signal alerts leave unhandled.
            </p>
            <div style={{ marginBottom: 28 }}>
              <ManualVsControlledDiagram />
            </div>
            <div
              style={{
                border: "1px solid var(--line-soft)",
                borderRadius: 10,
                overflow: "hidden",
              }}
            >
              <div
                className="grid grid-cols-2"
                style={{
                  padding: "10px 20px",
                  background: "var(--surface-2)",
                  borderBottom: "1px solid var(--line-soft)",
                }}
              >
                <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: ".10em", textTransform: "uppercase", color: "var(--muted)" }}>
                  Manual execution
                </div>
                <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: ".10em", textTransform: "uppercase", color: "var(--muted)" }}>
                  AQ Agent execution
                </div>
              </div>
              {(
                [
                  ["Lot size entered by hand", "Risk-based lot size calculated automatically"],
                  ["Order placed after reading the alert", "Order placed immediately on signal receipt"],
                  ["Breakeven moved manually, if at all", "Breakeven applied automatically after TP1 trigger"],
                  ["Signal tracked in memory or notes", "Execution state tracked and logged in the dashboard"],
                  ["Risk limits enforced by self-discipline", "Risk limits enforced by the engine before every order"],
                ] as [string, string][]
              ).map(([left, right], i, arr) => (
                <div
                  key={left}
                  className="grid grid-cols-2"
                  style={{
                    borderBottom: i < arr.length - 1 ? "1px solid var(--line-soft)" : "none",
                  }}
                >
                  <div
                    style={{
                      padding: "13px 20px",
                      fontSize: 13.5,
                      color: "var(--muted)",
                      borderRight: "1px solid var(--line-soft)",
                      lineHeight: 1.5,
                    }}
                  >
                    {left}
                  </div>
                  <div
                    style={{
                      padding: "13px 20px",
                      fontSize: 13.5,
                      color: "var(--text-soft)",
                      lineHeight: 1.5,
                    }}
                  >
                    {right}
                  </div>
                </div>
              ))}
            </div>
          </Container>
        </Section>

        {/* CTA */}
        <Section>
          <Container narrow>
            <div style={{ textAlign: "center" }}>
              <h2 style={{ ...T.h2, marginBottom: 12 }}>Start with the agent.</h2>
              <p style={{ ...T.body, fontSize: 14, marginBottom: 28 }}>
                Download the AQ Agent, sign in to activate your licence, and connect to MetaTrader 5.
              </p>
              <div style={{ display: "flex", gap: 10, justifyContent: "center", flexWrap: "wrap" }}>
                <Link
                  href="/login"
                  className="public-primary-button"
                  style={{
                    fontWeight: 700,
                    fontSize: 13.5,
                    padding: "8px 38px",
                    borderRadius: 8,
                    display: "inline-flex",
                    alignItems: "center",
                  }}
                >
                  Sign in
                </Link>
                <a
                  href={DOWNLOAD_URL}
                  download="AQAgentSetup.exe"
                  style={{
                    background: "var(--surface-2)",
                    color: "var(--text-soft)",
                    fontWeight: 600,
                    fontSize: 13.5,
                    padding: "8px 32px",
                    borderRadius: 8,
                    border: "1px solid var(--line)",
                    display: "inline-flex",
                    alignItems: "center",
                  }}
                >
                  Download AQ Agent
                </a>
              </div>
            </div>
          </Container>
        </Section>
      </main>
    </PublicShell>
  );
}
