import Link from "next/link";
import type { Metadata } from "next";
import {
  PublicShell,
  Container,
  Section,
  SectionLabel,
  PageHero,
  FlowStep,
  Callout,
  T,
  DOWNLOAD_URL,
  SITE_URL,
} from "@/components/public/shell";
import { ExecutionFlowDiagram } from "@/components/public/diagrams";

export const metadata: Metadata = {
  title: "How Apex Quantel Works | MT5 Signal Execution Flow",
  description:
    "Learn how Apex Quantel routes private trading signals through the gateway to a local Windows agent for MetaTrader 5 execution and risk-controlled trade management.",
  alternates: { canonical: "/how-it-works" },
  openGraph: {
    title: "How Apex Quantel Works | MT5 Signal Execution Flow",
    description:
      "Learn how Apex Quantel routes private trading signals through the gateway to a local Windows agent for MetaTrader 5 execution and risk-controlled trade management.",
    url: `${SITE_URL}/how-it-works`,
    siteName: "Apex Quantel",
    images: [{ url: `${SITE_URL}/apex-quantel-og.png`, width: 1200, height: 630, alt: "How Apex Quantel Works", type: "image/png" }],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "How Apex Quantel Works | MT5 Signal Execution Flow",
    description: "Signal routing, local execution, risk enforcement, and trade management - step by step.",
    images: [`${SITE_URL}/apex-quantel-og.png`],
  },
};

// ── Flow diagram ─────────────────────────────────────────────────────────────

// ── Page ─────────────────────────────────────────────────────────────────────

export default function HowItWorksPage() {
  return (
    <PublicShell>
      <main>
        <PageHero
          label="Execution flow"
          heading="How Apex Quantel works."
          sub="A step-by-step description of the signal-to-execution lifecycle - from signal creation to trade close and event logging."
        />

        {/* Flow diagram */}
        <Section surface>
          <Container>
            <SectionLabel text="System overview" />
            <h2 style={{ ...T.h2, marginBottom: 8 }}>The complete execution path.</h2>
            <p style={{ ...T.body, marginBottom: 40, maxWidth: 520 }}>
              Every executed trade follows this sequence. No steps are skipped. Failure at any
              stage stops execution and logs the reason.
            </p>
            <div style={{ display: "flex", justifyContent: "center" }}>
              <ExecutionFlowDiagram />
            </div>
          </Container>
        </Section>

        {/* Detailed steps */}
        <Section>
          <Container>
            <SectionLabel text="Step by step" />
            <h2 style={{ ...T.h2, marginBottom: 36 }}>Each stage in detail.</h2>

            <FlowStep n="01" title="Signal created">
              A trading signal is generated by the signal source from technical analysis. The signal
              contains the symbol (for example, XAUUSD), the direction (long or short), the entry
              price, the stop loss level, and one or more take-profit targets. The signal source
              operates independently of the execution system.
            </FlowStep>

            <FlowStep n="02" title="Signal sent to gateway">
              The signal is transmitted to the Apex Quantel gateway with a cryptographic signature
              that allows recipients to verify it has not been altered in transit. The gateway is
              the central routing point between the signal source and connected AQ Agents.
            </FlowStep>

            <FlowStep n="03" title="Licence verified">
              Before forwarding the signal, the gateway checks whether the connected user holds an
              active, valid licence. Signals are not distributed to unlicensed connections or
              accounts with lapsed access. This ensures the signal reaches only authorised
              installations.
            </FlowStep>

            <FlowStep n="04" title="Local AQ Agent receives signal">
              The AQ Agent, running on the user&apos;s Windows machine, receives the validated
              signal over a secure WebSocket connection from the gateway. The agent checks the
              signal age - signals older than the configured maximum age are discarded rather than
              executed late.
            </FlowStep>

            <FlowStep n="05" title="MT5 state is read">
              Before proceeding, the agent queries the locally connected MetaTrader 5 terminal for
              current state: account balance and equity, open positions on the signal&apos;s symbol,
              current spread, and whether the market is open for trading. This read happens in real
              time from the local terminal.
            </FlowStep>

            <FlowStep n="06" title="Risk engine validates the trade">
              The risk engine runs pre-trade checks using the current account state and the
              configured risk parameters. Checks include daily loss budget, losing streak count,
              symbol exposure limits, drawdown level, no-hedging rules, spread-to-SL ratio, and
              equity throttle state. If any check fails, the trade is rejected and the reason is
              logged. No order is placed.
            </FlowStep>

            <FlowStep n="07" title="Position size is calculated">
              If the trade passes all risk checks, the engine calculates the appropriate lot size.
              It takes the configured risk percent, applies it to the current account balance to
              determine the monetary risk amount, and then calculates the lot size based on the
              stop distance and the pip value of the symbol. The result is validated against minimum
              and maximum lot constraints.
            </FlowStep>

            <FlowStep n="08" title="Order is sent to MT5">
              The engine submits the order to MetaTrader 5 through the local API connection. The
              order includes the symbol, direction, calculated lot size, stop loss, and take-profit
              levels from the signal. The entry price used for stop and TP calculations is the
              original signal analysis entry, not the fill price, so execution levels remain
              consistent with the signal intent.
            </FlowStep>

            <FlowStep n="09" title="Trade is managed">
              Once a position is open, the engine monitors it at a configured polling interval. When
              the price reaches the TP1 trigger level, it executes the configured management
              actions: moving the stop loss to breakeven (the signal&apos;s original entry price)
              and optionally closing a partial portion of the position. The engine continues
              monitoring until the position closes at TP2, stop loss, or expiry.
            </FlowStep>

            <FlowStep n="10" title="Events are logged" last>
              Every significant event in the trade lifecycle is recorded: signal receipt, each
              risk check outcome, order placement, management actions, and final close. These events
              are visible in the dashboard, allowing the user to review exactly what happened for
              each signal.
            </FlowStep>

            <Callout type="important">
              Apex Quantel controls the execution layer. It does not control market conditions,
              signal quality, broker slippage, or trade outcomes. Trading financial instruments
              carries risk. Users are responsible for their accounts and the signals they choose
              to execute.
            </Callout>
          </Container>
        </Section>

        {/* CTA */}
        <Section surface>
          <Container narrow>
            <div style={{ textAlign: "center" }}>
              <h2 style={{ ...T.h2, marginBottom: 12 }}>Start with the agent.</h2>
              <p style={{ ...T.body, fontSize: 14, marginBottom: 28 }}>
                Download the AQ Agent, sign in to activate your licence, and connect to MetaTrader 5.
              </p>
              <div style={{ display: "flex", gap: 10, justifyContent: "center", flexWrap: "wrap" }}>
                <Link
                  href="/login"
                  className="public-primary-button"
                  style={{
                    fontWeight: 700,
                    fontSize: 13.5,
                    padding: "8px 38px",
                    borderRadius: 8,
                    display: "inline-flex",
                    alignItems: "center",
                  }}
                >
                  Sign in
                </Link>
                <a
                  href={DOWNLOAD_URL}
                  download="AQAgentSetup.exe"
                  style={{
                    background: "var(--surface-2)",
                    color: "var(--text-soft)",
                    fontWeight: 600,
                    fontSize: 13.5,
                    padding: "8px 32px",
                    borderRadius: 8,
                    border: "1px solid var(--line)",
                    display: "inline-flex",
                    alignItems: "center",
                  }}
                >
                  Download AQ Agent
                </a>
              </div>
            </div>
          </Container>
        </Section>
      </main>
    </PublicShell>
  );
}
