import type { Metadata } from "next";
import {
  PublicShell,
  Container,
  Section,
  PageHero,
  ProseSection,
  Callout,
  T,
  SITE_URL,
} from "@/components/public/shell";

export const metadata: Metadata = {
  title: "Privacy Policy | Apex Quantel",
  description:
    "Read how Apex Quantel handles account data, licence information, technical logs, and privacy-related platform information.",
  alternates: { canonical: "/privacy" },
  openGraph: {
    title: "Privacy Policy | Apex Quantel",
    description: "How Apex Quantel handles account data, licence information, and platform privacy.",
    url: `${SITE_URL}/privacy`,
    siteName: "Apex Quantel",
    images: [{ url: `${SITE_URL}/apex-quantel-og.png`, width: 1200, height: 630, alt: "Apex Quantel Privacy Policy", type: "image/png" }],
    type: "website",
  },
};

function Li({ children }: { children: React.ReactNode }) {
  return (
    <li
      style={{
        display: "flex",
        alignItems: "flex-start",
        gap: 10,
        marginBottom: 8,
        fontSize: 13.5,
        color: "var(--muted)",
        lineHeight: 1.7,
      }}
    >
      <span style={{ width: 4, height: 4, borderRadius: "50%", background: "var(--line-strong)", marginTop: 9, flexShrink: 0 }} />
      <span>{children}</span>
    </li>
  );
}

export default function PrivacyPage() {
  return (
    <PublicShell>
      <main>
        <PageHero
          label="Legal"
          heading="Privacy Policy."
          sub="This policy describes what information Apex Quantel collects, how it is used, and how it is handled."
        />

        <Section>
          <Container narrow>
            <div style={{ fontSize: 12, color: "var(--muted)", marginBottom: 40, paddingBottom: 20, borderBottom: "1px solid var(--line-soft)" }}>
              Last updated: June 2026
            </div>

            <div>
              <ProseSection heading="1. Overview">
                <p>
                  Apex Quantel (&quot;we&quot;, &quot;the Platform&quot;) is committed to handling
                  your information responsibly. This policy applies to the web dashboard and the
                  Apex Quantel gateway. It does not cover the AQ Agent, which runs entirely on
                  your local machine and does not transmit personal data to our servers beyond
                  what is described here.
                </p>
              </ProseSection>

              <ProseSection heading="2. Information we collect">
                <p>We collect and store the following categories of information:</p>
                <ul style={{ margin: "12px 0 16px", padding: 0, listStyle: "none" }}>
                  <Li>
                    <strong style={{ color: "var(--text-soft)" }}>Account information:</strong>{" "}
                    Your email address, collected at sign-up for authentication purposes. Authentication
                    is provided by Supabase, which stores your session and account data on our behalf.
                  </Li>
                  <Li>
                    <strong style={{ color: "var(--text-soft)" }}>Licence data:</strong>{" "}
                    Your licence key, subscription status, activation history, and the agent
                    installation associated with your account.
                  </Li>
                  <Li>
                    <strong style={{ color: "var(--text-soft)" }}>Billing information:</strong>{" "}
                    Subscription and payment status. Payment processing is handled by a third-party
                    processor. We do not store your card details.
                  </Li>
                  <Li>
                    <strong style={{ color: "var(--text-soft)" }}>Execution telemetry:</strong>{" "}
                    Execution events, signal receipt records, trade outcomes, and rejection logs
                    generated by your AQ Agent and displayed in the dashboard.
                  </Li>
                  <Li>
                    <strong style={{ color: "var(--text-soft)" }}>Technical logs:</strong>{" "}
                    Gateway connection logs, agent session records, and error logs used for
                    debugging and support.
                  </Li>
                </ul>
              </ProseSection>

              <ProseSection heading="3. What we do not collect">
                <p>
                  <strong style={{ color: "var(--text-soft)" }}>MT5 credentials:</strong>{" "}
                  Your MetaTrader 5 broker login and password are entered into the AQ Agent on your
                  local machine. They are used by the agent to connect to your locally running MT5
                  terminal. They are not transmitted to Apex Quantel servers.
                </p>
                <p style={{ marginTop: 12 }}>
                  <strong style={{ color: "var(--text-soft)" }}>Raw MT5 account data:</strong>{" "}
                  We do not pull or store your full MT5 account history, trade records from your
                  broker, or account balance data outside of the execution events generated by the
                  agent during its operation.
                </p>
              </ProseSection>

              <ProseSection heading="4. How we use your information">
                <p>We use collected information to:</p>
                <ul style={{ margin: "12px 0", padding: 0, listStyle: "none" }}>
                  <Li>Authenticate your account and manage session access</Li>
                  <Li>Validate and enforce licence entitlements</Li>
                  <Li>Route signals to your connected AQ Agent</Li>
                  <Li>Process billing and manage subscriptions</Li>
                  <Li>Display execution events and history in the dashboard</Li>
                  <Li>Diagnose technical issues and provide support</Li>
                  <Li>Communicate platform updates or changes to these policies</Li>
                </ul>
                <p style={{ marginTop: 12 }}>
                  We do not sell your data to third parties. We do not use your data for
                  advertising.
                </p>
              </ProseSection>

              <ProseSection heading="5. Third-party services">
                <p>The Platform uses the following third-party services:</p>
                <ul style={{ margin: "12px 0", padding: 0, listStyle: "none" }}>
                  <Li>
                    <strong style={{ color: "var(--text-soft)" }}>Supabase:</strong>{" "}
                    Provides authentication and database storage. Your account data is stored in
                    Supabase infrastructure. Their privacy policy applies: supabase.com/privacy.
                  </Li>
                  <Li>
                    <strong style={{ color: "var(--text-soft)" }}>Payment processor:</strong>{" "}
                    Handles subscription billing. Their privacy policy applies to payment-related
                    data.
                  </Li>
                </ul>
                <p style={{ marginTop: 12 }}>
                  MetaTrader 5 is a product of MetaQuotes Software Corp. and operates under their
                  own terms. Your broker also has its own data handling practices.
                </p>
              </ProseSection>

              <ProseSection heading="6. Cookies and local storage">
                <p>
                  The dashboard uses local storage and session storage for authentication state
                  management. We do not use third-party tracking cookies or advertising pixels.
                </p>
              </ProseSection>

              <ProseSection heading="7. Data retention">
                <p>
                  Account data, licence records, and execution telemetry are retained while your
                  account is active. If you request account deletion, we will remove your personal
                  data subject to any legal obligations that require us to retain certain records.
                </p>
              </ProseSection>

              <ProseSection heading="8. Your rights">
                <p>You have the right to:</p>
                <ul style={{ margin: "12px 0", padding: 0, listStyle: "none" }}>
                  <Li>Access the personal data we hold about you</Li>
                  <Li>Request correction of inaccurate data</Li>
                  <Li>Request deletion of your account and associated data</Li>
                  <Li>Object to processing in certain circumstances</Li>
                </ul>
                <p style={{ marginTop: 12 }}>
                  To exercise these rights, contact us through the support channel in your
                  dashboard.
                </p>
              </ProseSection>

              <ProseSection heading="9. Changes to this policy">
                <p>
                  We may update this Privacy Policy from time to time. Where changes are material,
                  we will provide notice through the dashboard or by email. Continued use of the
                  Platform after the updated policy is published constitutes acceptance.
                </p>
              </ProseSection>

              <ProseSection heading="10. Contact">
                <p>
                  For privacy-related questions or data requests, contact us through the support
                  channel available in your dashboard after signing in.
                </p>
              </ProseSection>
            </div>

            <Callout type="note">
              This privacy policy describes our current practices and intent. As the platform
              evolves, this policy will be updated. We recommend reviewing it periodically.
            </Callout>

            <div
              style={{
                marginTop: 32,
                paddingTop: 24,
                borderTop: "1px solid var(--line-soft)",
                fontSize: 12,
                color: "var(--muted)",
                lineHeight: 1.7,
              }}
            >
              <span style={{ ...T.label, display: "inline-block", marginBottom: 8 }}>Legal review note</span>
              <p style={{ margin: 0 }}>
                This privacy policy is provided as a plain-language starting point. We recommend
                having it reviewed by a qualified legal professional, particularly if operating in
                jurisdictions with specific data protection requirements such as GDPR.
              </p>
            </div>
          </Container>
        </Section>
      </main>
    </PublicShell>
  );
}
